all:
	#@del CyAPI.*
	D:\Qt\Qt5.5.0\Tools\mingw492_32\bin\g++ ../src/CyAPI.cpp -lsetupapi -I ../inc -c -o ../target/CyAPI.o -Wno-conversion-null
	ar rcs ../target/CyAPI.a ../target/CyAPI.o
	echo ../target/CyAPI.a generated...
